In [1]:
import tensorflow as tf

In [2]:
print(tf.__version__)  # 打印TensorFlow版本号

2.17.0


In [3]:
tf.add(1, 2).numpy()

3

In [4]:
hello = tf.constant('Hello, TensorFlow!')

In [5]:
hello.numpy()

b'Hello, TensorFlow!'

# mnist demo

In [6]:
mnist = tf.keras.datasets.mnist

In [7]:
(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

Exception: URL fetch failure on https://storage.googleapis.com/tensorflow/tf-keras-datasets/mnist.npz: None -- [SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1000)

In [9]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

In [10]:
predictions = model(x_train[:1]).numpy()
predictions

NameError: name 'x_train' is not defined

In [6]:
tf.nn.softmax(predictions).numpy()

array([[0.09098404, 0.11688492, 0.10999359, 0.05546666, 0.0755544 ,
        0.09761093, 0.13591442, 0.12180438, 0.11113615, 0.08465055]],
      dtype=float32)

In [7]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [8]:
loss_fn(y_train[:1], predictions).numpy()

2.3267658

In [9]:
model.compile(optimizer='adam',
       loss=loss_fn,
       metrics=['accuracy'])

In [10]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 7s 3ms/step - accuracy: 0.8580 - loss: 0.4897
Epoch 2/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - accuracy: 0.9546 - loss: 0.1509
Epoch 3/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - accuracy: 0.9661 - loss: 0.1095
Epoch 4/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - accuracy: 0.9732 - loss: 0.0845
Epoch 5/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - accuracy: 0.9768 - loss: 0.0750


In [11]:
model.evaluate(x_test,  y_test, verbose=2)

313/313 - 1s - 4ms/step - accuracy: 0.9777 - loss: 0.0761


[0.07606913149356842, 0.9776999950408936]

In [12]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

In [13]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[1.01356335e-07, 2.04640696e-08, 4.93189509e-06, 7.15693750e-05,
        5.18585903e-11, 3.54355905e-07, 1.87401127e-14, 9.99914527e-01,
        1.21177175e-06, 7.36822130e-06],
       [1.44118687e-07, 2.55366613e-04, 9.99727786e-01, 1.36592435e-05,
        1.13508450e-16, 1.53444194e-06, 8.10512102e-10, 1.68922303e-13,
        1.54986958e-06, 2.59750473e-13],
       [1.07849053e-06, 9.98574376e-01, 8.81250453e-05, 1.73448261e-05,
        5.03050760e-05, 7.83919677e-06, 4.27817849e-06, 5.54685190e-04,
        6.97059731e-04, 4.87286434e-06],
       [9.99980330e-01, 5.20795129e-10, 6.58210593e-06, 1.67724167e-07,
        7.26577127e-08, 2.19247181e-06, 3.41491454e-06, 4.91632318e-06,
        5.67155989e-10, 2.22495828e-06],
       [6.49291962e-07, 3.37569483e-09, 7.89155001e-06, 2.47505536e-08,
        9.95971859e-01, 5.46492743e-07, 3.77447861e-07, 5.11694670e-05,
        2.59561011e-06, 3.96491261e-03]], dtype=float32)>

In [14]:
y_test[:5]

array([7, 2, 1, 0, 4], dtype=uint8)